version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "drizzle-orm"
        update-types: ["version-update:semver-major"]
      - dependency-name: "drizzle-kit"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
